#!/usr/bin/env bash
#updating and installinggit add .
apt update
apt install -y apache2
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
echo "service apache2 start" >> ~/.bashrc
