#!/usr/bin/env bash
# Loadbalancer

function install() {
    command -v "$1" &> /dev/null

    #shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

install haproxy # Install HAProxy

echo -e "\nSetting up some minor stuff.\n"

# Backup the default server config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Define the server configuration
server_config=\
"
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
"

# Write the server configuration to haproxy.cfg
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

echo "Configured - Roundrobin on web-01 & web-02"

# Start or restart HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

echo -e "HAProxy is running.\n"

# Print the servers for confirmation
echo "Servers configured:"
echo "web-01: [STUDENT_ID]-web-01"
echo "web-02: [STUDENT_ID]-web-02"
